import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

PreferredSize rideShareAppBar({
  required BuildContext context,
  Widget? child,
  Widget? leading,
  bool? automaticallyImplyLeading,
  Widget? title,
  List<Widget>? actions,
  Widget? flexibleSpace,
  PreferredSizeWidget? bottom,
  double? elevation,
  double? scrolledUnderElevation,
  ScrollNotificationPredicate? notificationPredicate,
  Color? shadowColor,
  Color? surfaceTintColor,
  ShapeBorder? shape,
  Color? backgroundColor,
  Color? foregroundColor,
  Brightness? brightness,
  IconThemeData? iconTheme,
  IconThemeData? actionsIconTheme,
  TextTheme? textTheme,
  bool? primary,
  bool? centerTitle,
  bool? excludeHeaderSemantics,
  double? titleSpacing,
  double? toolbarOpacity,
  double? bottomOpacity,
  Size? preferredSize,
  double? toolbarHeight,
  double? leadingWidth,
  bool? backwardsCompatibility,
  TextStyle? toolbarTextStyle,
  TextStyle? titleTextStyle,
}) {
  return PreferredSize(
    preferredSize: preferredSize ?? Size.fromHeight(60.h),
    child: AppBar(
      backgroundColor: backgroundColor ?? Colors.white,
      actions: actions,
      leading: leading,
      elevation: elevation,
      title: title,
      centerTitle: centerTitle ?? true,
      automaticallyImplyLeading: automaticallyImplyLeading ?? true,
    ),
  );
}
